version: "3.4"

services:
  jenkins:
    build: .
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    restart: unless-stopped

volumes:
  jenkins_home:
    name: jenkins_home
